export const ADD_INGREDIENT_INSIDE_CONSTRUCTOR: 'ADD_INGREDIENT_INSIDE_CONSTRUCTOR' = 'ADD_INGREDIENT_INSIDE_CONSTRUCTOR';
export const REMOVE_INGREDIENT_INSIDE_CONSTRUCTOR: 'REMOVE_INGREDIENT_INSIDE_CONSTRUCTOR' = 'REMOVE_INGREDIENT_INSIDE_CONSTRUCTOR';
export const TOGGLE_BUN_INSIDE_CONSTRUCTOR: 'TOGGLE_BUN_INSIDE_CONSTRUCTOR' = 'TOGGLE_BUN_INSIDE_CONSTRUCTOR';
export const CHANGE_INGREDIENT_POSITION: 'CHANGE_INGREDIENT_POSITION' = 'CHANGE_INGREDIENT_POSITION';
