export const POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS' = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILED: 'POST_ORDER_FAILED' = 'POST_ORDER_FAILED';
export const HANDLE_CLOSE_ORDER_MODAL: 'HANDLE_CLOSE_ORDER_MODAL' = 'HANDLE_CLOSE_ORDER_MODAL';
export const POST_ORDER_REQUEST: 'POST_ORDER_REQUEST' = 'POST_ORDER_REQUEST';
export const ADD_CURRENT_ORDER_DETAILS: 'ADD_CURRENT_ORDER_DETAILS' = 'ADD_CURRENT_ORDER_DETAILS';
export const REMOVE_CURRENT_ORDER_DETAILS: 'REMOVE_CURRENT_ORDER_DETAILS' = 'REMOVE_CURRENT_ORDER_DETAILS';
