export const POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS' = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILED: 'POST_ORDER_FAILED' = 'POST_ORDER_FAILED';
export const HANDLE_CLOSE_ORDER_MODAL: 'HANDLE_CLOSE_ORDER_MODAL' = 'HANDLE_CLOSE_ORDER_MODAL';
export const POST_ORDER_REQUEST: 'POST_ORDER_REQUEST' = 'POST_ORDER_REQUEST';
